# Generated by Django 5.0.6 on 2024-06-12 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Committees',
                'db_table': 'committees',
            },
        ),
        migrations.CreateModel(
            name='GenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Genders',
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='PositionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Position',
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='SpeakersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=765)),
                ('image', models.ImageField(upload_to='speakers_images/%y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'Speakers',
                'db_table': 'speakers',
            },
        ),
        migrations.CreateModel(
            name='UniversitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'db_table': 'universities',
            },
        ),
        migrations.CreateModel(
            name='CommitteeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='committee_images/%y/%m/%d/')),
                ('committee_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ITAS.committeegroupmodel')),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ITAS.gendermodel')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ITAS.positionsmodel')),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ITAS.universitiesmodel')),
            ],
            options={
                'verbose_name_plural': 'Committee',
                'db_table': 'committee',
            },
        ),
    ]
