# Generated by Django 5.0.6 on 2024-06-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceDaysModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SponsorPartnersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sponsor_and_partners/%y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'Sponsor and Partners',
                'db_table': 'sponsor_partners',
            },
        ),
        migrations.CreateModel(
            name='ConferenceAgendaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('oclock', models.CharField(max_length=30)),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_conference.conferencedaysmodel')),
            ],
            options={
                'verbose_name_plural': 'Conference Agenda',
                'db_table': 'conference_agenda',
            },
        ),
    ]
