# Generated by Django 5.0.6 on 2024-06-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_coordinator', models.JSONField()),
                ('phone_numbers', models.JSONField()),
                ('emails', models.JSONField()),
                ('location', models.CharField(max_length=765)),
            ],
            options={
                'verbose_name_plural': 'About',
                'db_table': 'about',
            },
        ),
    ]
